export { default as AccountInfo } from './AccountInfo.vue'
export { default as DriveInfo } from './DriveInfo.vue'
export { default as HallInfo } from './HallInfo.vue'
export { default as MapInfo } from './MapInfo.vue'
export { default as PoemInfo } from './PoemInfo.vue'
export { default as TitleInfo } from './TitleInfo.vue'
export { default as WelcomeInfo } from './WelcomeInfo.vue'
